version: '3.1'

services:
  db-dev:
    image: anilbostanci/crowd-db-staging:latest
    #If you're on an arm/arm64 architecture use the image below (M1 macbook)
    #image: anilbostanci/crowd-db-staging:latest-arm
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crowd-web
    ports:
      - 5433:5432
    volumes:
      - pgdata-test:/var/lib/postgresql/data

volumes:
  pgdata-test:
