version: '3.1'

services:
  db-dev:
    image: anilbostanci/crowd-db-staging:latest
    #If you're on an arm/arm64 architecture use the image below (M1 macbook)
    #image: anilbostanci/crowd-db-staging:latest-arm
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crowd-web
    ports:
      - 5432:5432
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  search-engine:
    image: getmeili/meilisearch:v0.27.2
    ports:
      - 7700:7700
    volumes:
      - search-dev:/data.ms

volumes:
  pgdata-dev:
