version: '3.1'

services:
  crowd-frontend:
    volumes:
      - ../frontend:/usr/crowd/frontend

  crowd-backend:
    volumes:
      - ../backend:/usr/crowd/backend
      - exclude-be:/usr/crowd/backend/node_modules

  crowd-conversations:
    volumes:
      - ../premium/conversations:/usr/crowd/conversations

  sls-deployer-integrations:
    volumes:
      - ../backend:/usr/crowd/backend

  sls-deployer-nodejs-microservices:
    volumes:
      - ../backend:/usr/crowd/backend

  sls-deployer-python-microservices:
    volumes:
      - ../backend:/usr/crowd/backend

  sls-deployer-dbOperations:
    volumes:
      - ../backend:/usr/crowd/backend
