version: '3.1'

services:

  cubejs:
    image: crowddotdev/cubejs:${CROWD_VERSION}
    env_file:
      - ../backend/.env.staging
    build:
      context: ../backend/src/cubejs
      dockerfile: Dockerfile-cubejs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2Gb

  nginx:
    image: crowddotdev/nginx:${CROWD_VERSION}
    build:
      context: ../nginx
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_CROWD_BACKEND_DOMAIN=anton-staging.crowd.dev
      - NGINX_CROWD_CUBEJS_DOMAIN=cubejs-staging.crowd.dev
    depends_on:
      - crowd-backend
      - cubejs

  crowd-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile-backend
    image: crowddotdev/backend:${CROWD_VERSION}
    dns: 1.1.1.1
    env_file:
      - ../backend/.env.staging
    working_dir: /usr/crowd/backend/dist
    command: >
        sh -c "npm run db:create:dev:build && 
               node server.js"
    environment:
      - DOCKER_BUILDKIT=1
    depends_on:
      - db

  search-engine:
    image: getmeili/meilisearch:v0.27.2
    ports:
      - 7700:7700
    volumes:
      - search-dev:/data.ms

volumes:
  search-dev:
